name: Ledger
author: DaytonJWatson
description: Ledger gamemode
version: 0.0.1
api-version: '1.21'
main: com.daytonjwatson.ledger.LedgerPlugin
commands:
  sell:
    description: Sell items at spawn.
    usage: /sell [inventory|hand]
  bank:
    description: Bank deposit commands.
    usage: /bank deposit <amount|all>
  balance:
    description: View carried and banked money.
    usage: /balance
  tool:
    description: Tool vendor actions.
    usage: /tool buy <type> <tier> [variant] | /tool repair
