name: Ledger
author: DaytonJWatson
description: Ledger gamemode
version: 0.0.1
api-version: '1.21'
main: com.daytonjwatson.ledger.LedgerPlugin
commands:
  sell:
    description: Open the sell menu.
    usage: /sell
  bank:
    description: Open the bank menu.
    usage: /bank
  balance:
    description: View carried and banked money.
    usage: /balance
  tool:
    description: Tool vendor actions.
    usage: /tool buy <type> <tier> [variant] | /tool repair
  tools:
    description: Open the tools menu.
    usage: /tools
  repair:
    description: Open the repair menu.
    usage: /repair
  upgrades:
    description: Open the upgrades menu.
    usage: /upgrades
  upgrade:
    description: Purchase upgrades.
    usage: /upgrade buy <id>
  ledger:
    description: Open the Ledger hub menu.
    usage: /ledger
